# Generated by Django 5.0.7 on 2024-08-23 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logs',
            name='params',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
