# Generated by Django 5.0.7 on 2024-08-01 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directories', '0002_rename_items2_items_alter_items_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='inv_series',
            name='schema',
            field=models.ImageField(blank=True, null=True, upload_to='inv_series_schema', verbose_name='Схема'),
        ),
    ]
