# Generated by Django 5.0.7 on 2024-09-16 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directories', '0005_alter_companies_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inv_spec_of_in_out',
            name='info',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Описание входа'),
        ),
    ]
