# Generated by Django 5.0.7 on 2024-07-31 15:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('directories', '0002_rename_items2_items_alter_items_table'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInvConfigs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('options', models.TextField(blank=True, max_length=4000, null=True)),
                ('invertor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='directories.invertors')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Конфигурация ПЧ пользователя',
                'verbose_name_plural': 'Конфигурации ПЧ пользователя',
                'db_table': 'd_user_inv_config',
            },
        ),
    ]
