# Generated by Django 5.0.7 on 2024-08-14 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userconfigs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinvconfigs',
            name='staff_opened',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
