# Generated by Django 5.0.7 on 2024-08-21 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userconfigs', '0002_userinvconfigs_staff_opened'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinvconfigs',
            name='invertor_discount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
        migrations.AddField(
            model_name='userinvconfigs',
            name='invertor_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='userinvconfigs',
            name='options_disccounts',
            field=models.TextField(blank=True, max_length=4000, null=True),
        ),
        migrations.AddField(
            model_name='userinvconfigs',
            name='options_prices',
            field=models.TextField(blank=True, max_length=4000, null=True),
        ),
    ]
