# Generated by Django 5.0.7 on 2024-08-22 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userconfigs', '0003_userinvconfigs_invertor_discount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinvconfigs',
            name='info',
            field=models.CharField(blank=True, max_length=4000, null=True),
        ),
    ]
